# coding: utf-8

"""
    One-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from bsg_api.models.short_link import ShortLink
from typing import Optional, Set
from typing_extensions import Self

class Sms(BaseModel):
    """
    Sms
    """ # noqa: E501
    sender: StrictStr = Field(description="Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)")
    text: Annotated[str, Field(strict=True, max_length=765)] = Field(description="SMS text, max length is 765 chars for GSM 7-bit encoding (Latin), and 355 for UCS-2")
    unsubscribe_caption: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Caption before unsubscribe link. Space between caption and link is required.")
    transliterate: Optional[StrictBool] = Field(default=False, description="apply transliteration to sms text if it necessary")
    short_links: Optional[List[ShortLink]] = Field(default=None, description="$shortLinks")
    __properties: ClassVar[List[str]] = ["sender", "text", "unsubscribe_caption", "transliterate", "short_links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sms from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in short_links (list)
        _items = []
        if self.short_links:
            for _item_short_links in self.short_links:
                if _item_short_links:
                    _items.append(_item_short_links.to_dict())
            _dict['short_links'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sms from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sender": obj.get("sender"),
            "text": obj.get("text"),
            "unsubscribe_caption": obj.get("unsubscribe_caption"),
            "transliterate": obj.get("transliterate") if obj.get("transliterate") is not None else False,
            "short_links": [ShortLink.from_dict(_item) for _item in obj["short_links"]] if obj.get("short_links") is not None else None
        })
        return _obj


