# coding: utf-8

"""
    One-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Viber(BaseModel):
    """
    Viber
    """ # noqa: E501
    sender: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=40)]]
    text: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=1000)]]
    image_url: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    button_caption: Optional[Annotated[str, Field(strict=True, max_length=20)]] = None
    link_url: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Required if button_caption is set")
    __properties: ClassVar[List[str]] = ["sender", "text", "image_url", "button_caption", "link_url"]

    @field_validator('image_url')
    def image_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(http|https):\/\/([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+(:(\d+))?([-_\/A-Z0-9?=&]*)?(\.jpg|\.png|\.tiff|\.jpeg|\.gif|\.bmp){1}$", value ,re.IGNORECASE):
            raise ValueError(r"must validate the regular expression /^(http|https):\/\/([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+(:(\d+))?([-_\/A-Z0-9?=&]*)?(\.jpg|\.png|\.tiff|\.jpeg|\.gif|\.bmp){1}$/iD")
        return value

    @field_validator('link_url')
    def link_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(https?:\/\/)?([\p{L}\d\.-]+)\.([\p{L}\.]{2,50})([\/\w \.-]*)*\/?", value ,re.IGNORECASE ,re.UNICODE):
            raise ValueError(r"must validate the regular expression /^(https?:\/\/)?([\p{L}\d\.-]+)\.([\p{L}\.]{2,50})([\/\w \.-]*)*\/?/iu")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Viber from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sender (nullable) is None
        # and model_fields_set contains the field
        if self.sender is None and "sender" in self.model_fields_set:
            _dict['sender'] = None

        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Viber from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sender": obj.get("sender"),
            "text": obj.get("text"),
            "image_url": obj.get("image_url"),
            "button_caption": obj.get("button_caption"),
            "link_url": obj.get("link_url")
        })
        return _obj


