# flake8: noqa

# import apis into api package
from bsg_api.api.account_settings_api import AccountSettingsApi
from bsg_api.api.auth_api import AuthApi
from bsg_api.api.balance_api import BalanceApi
from bsg_api.api.campaign_api import CampaignApi
from bsg_api.api.campaign_rcs_api import CampaignRCSApi
from bsg_api.api.campaign_sms_api import CampaignSMSApi
from bsg_api.api.campaign_viber_api import CampaignViberApi
from bsg_api.api.campaign_whats_app_api import CampaignWhatsAppApi
from bsg_api.api.contact_api import ContactApi
from bsg_api.api.contact_field_api import ContactFieldApi
from bsg_api.api.contact_list_api import ContactListApi
from bsg_api.api.email_api import EmailApi
from bsg_api.api.message_rcs_api import MessageRCSApi
from bsg_api.api.messages_api import MessagesApi
from bsg_api.api.messages_sms_api import MessagesSMSApi
from bsg_api.api.messages_whats_app_api import MessagesWhatsAppApi
from bsg_api.api.senders_api import SendersApi
from bsg_api.api.short_domains_api import ShortDomainsApi
from bsg_api.api.short_links_api import ShortLinksApi
from bsg_api.api.statistic_api import StatisticApi
from bsg_api.api.stop_list_api import StopListApi
from bsg_api.api.two_faotp_api import TwoFAOTPApi
from bsg_api.api.two_fa_templates_api import TwoFATemplatesApi
from bsg_api.api.account_balance_api import AccountBalanceApi
from bsg_api.api.account_tariffs_api import AccountTariffsApi
from bsg_api.api.campaign_details_api import CampaignDetailsApi
from bsg_api.api.campaign_price_api import CampaignPriceApi
from bsg_api.api.campaign_stop_api import CampaignStopApi
from bsg_api.api.campaign_tag_api import CampaignTagApi
from bsg_api.api.campaigns_api import CampaignsApi
from bsg_api.api.cancel_otp_api import CancelOtpApi
from bsg_api.api.contact_create_api import ContactCreateApi
from bsg_api.api.contact_delete_api import ContactDeleteApi
from bsg_api.api.contact_field_create_api import ContactFieldCreateApi
from bsg_api.api.contact_field_update_api import ContactFieldUpdateApi
from bsg_api.api.contact_fields_api import ContactFieldsApi
from bsg_api.api.contact_list_attach_api import ContactListAttachApi
from bsg_api.api.contact_list_create_api import ContactListCreateApi
from bsg_api.api.contact_list_delete_api import ContactListDeleteApi
from bsg_api.api.contact_list_detach_api import ContactListDetachApi
from bsg_api.api.contact_list_search_api import ContactListSearchApi
from bsg_api.api.contact_list_tag_api import ContactListTagApi
from bsg_api.api.contact_list_update_api import ContactListUpdateApi
from bsg_api.api.contact_lists_api import ContactListsApi
from bsg_api.api.contact_tag_api import ContactTagApi
from bsg_api.api.contact_update_api import ContactUpdateApi
from bsg_api.api.contacts_api import ContactsApi
from bsg_api.api.contacts_delete_api import ContactsDeleteApi
from bsg_api.api.contacts_search_api import ContactsSearchApi
from bsg_api.api.email_send_api import EmailSendApi
from bsg_api.api.email_template_send_api import EmailTemplateSendApi
from bsg_api.api.get_messages_api import GetMessagesApi
from bsg_api.api.get_settings_address_book_fields_by_id_api import GetSettingsAddressBookFieldsByIdApi
from bsg_api.api.login_api import LoginApi
from bsg_api.api.otp_list_api import OtpListApi
from bsg_api.api.otp_template_api import OtpTemplateApi
from bsg_api.api.otp_template_create_api import OtpTemplateCreateApi
from bsg_api.api.otp_template_delete_api import OtpTemplateDeleteApi
from bsg_api.api.otp_template_list_api import OtpTemplateListApi
from bsg_api.api.post_campaigns_whatsapp_send_api import PostCampaignsWhatsappSendApi
from bsg_api.api.post_contacts_fields_delete_api import PostContactsFieldsDeleteApi
from bsg_api.api.rcs_send_groups_api import RcsSendGroupsApi
from bsg_api.api.rcs_single_api import RcsSingleApi
from bsg_api.api.refresh_token_api import RefreshTokenApi
from bsg_api.api.resend_otp_api import ResendOtpApi
from bsg_api.api.send_otp_api import SendOtpApi
from bsg_api.api.sender_request_legal_api import SenderRequestLegalApi
from bsg_api.api.sender_request_natural_api import SenderRequestNaturalApi
from bsg_api.api.sender_requests_api import SenderRequestsApi
from bsg_api.api.senders_tag_api import SendersTagApi
from bsg_api.api.short_urls_clicks_api import ShortUrlsClicksApi
from bsg_api.api.short_urls_domain_api import ShortUrlsDomainApi
from bsg_api.api.short_urls_domain_create_api import ShortUrlsDomainCreateApi
from bsg_api.api.short_urls_domain_remove_api import ShortUrlsDomainRemoveApi
from bsg_api.api.short_urls_domain_update_api import ShortUrlsDomainUpdateApi
from bsg_api.api.short_urls_domains_api import ShortUrlsDomainsApi
from bsg_api.api.short_urls_link_api import ShortUrlsLinkApi
from bsg_api.api.short_urls_link_create_api import ShortUrlsLinkCreateApi
from bsg_api.api.short_urls_link_delete_api import ShortUrlsLinkDeleteApi
from bsg_api.api.short_urls_link_update_api import ShortUrlsLinkUpdateApi
from bsg_api.api.short_urls_links_api import ShortUrlsLinksApi
from bsg_api.api.sms_send_api import SmsSendApi
from bsg_api.api.sms_send_groups_api import SmsSendGroupsApi
from bsg_api.api.sms_send_individual_api import SmsSendIndividualApi
from bsg_api.api.status_otp_api import StatusOtpApi
from bsg_api.api.stoplist_add_api import StoplistAddApi
from bsg_api.api.stoplist_items_api import StoplistItemsApi
from bsg_api.api.stoplist_remove_api import StoplistRemoveApi
from bsg_api.api.stoplist_search_api import StoplistSearchApi
from bsg_api.api.verify_otp_api import VerifyOtpApi

