# coding: utf-8

"""
    One-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from bsg_api.models.otp_channel import OtpChannel
from bsg_api.models.otp_list200_response import OtpList200Response
from bsg_api.models.otp_status import OtpStatus
from bsg_api.models.sort_way import SortWay

from bsg_api.api_client import ApiClient, RequestSerialized
from bsg_api.api_response import ApiResponse
from bsg_api.rest import RESTResponseType


class OtpListApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def otp_list(
        self,
        filter_from: Annotated[date, Field(description="Period start date (date and time when the authentication session was created) in ISO 8601 format.")],
        filter_to: Annotated[date, Field(description="End date of the period (date and time when the authentication was created) in ISO 8601 format.")],
        page_offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        page_limit: Optional[Annotated[int, Field(le=500, strict=True, ge=10)]] = None,
        filter_ids: Annotated[Optional[Annotated[List[StrictStr], Field(min_length=1, max_length=3)]], Field(description="Authentication ID. The maximum number is 3.")] = None,
        filter_status: Optional[OtpStatus] = None,
        filter_channel: Optional[OtpChannel] = None,
        filter_recipient: Optional[StrictStr] = None,
        filter_country_code: Optional[StrictStr] = None,
        way: Optional[SortWay] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> OtpList200Response:
        """List of authentication sessions

        Use to get a list of authentications for a period.

        :param filter_from: Period start date (date and time when the authentication session was created) in ISO 8601 format. (required)
        :type filter_from: date
        :param filter_to: End date of the period (date and time when the authentication was created) in ISO 8601 format. (required)
        :type filter_to: date
        :param page_offset:
        :type page_offset: int
        :param page_limit:
        :type page_limit: int
        :param filter_ids: Authentication ID. The maximum number is 3.
        :type filter_ids: List[str]
        :param filter_status:
        :type filter_status: OtpStatus
        :param filter_channel:
        :type filter_channel: OtpChannel
        :param filter_recipient:
        :type filter_recipient: str
        :param filter_country_code:
        :type filter_country_code: str
        :param way:
        :type way: SortWay
        :param sort: Sort by
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._otp_list_serialize(
            filter_from=filter_from,
            filter_to=filter_to,
            page_offset=page_offset,
            page_limit=page_limit,
            filter_ids=filter_ids,
            filter_status=filter_status,
            filter_channel=filter_channel,
            filter_recipient=filter_recipient,
            filter_country_code=filter_country_code,
            way=way,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OtpList200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def otp_list_with_http_info(
        self,
        filter_from: Annotated[date, Field(description="Period start date (date and time when the authentication session was created) in ISO 8601 format.")],
        filter_to: Annotated[date, Field(description="End date of the period (date and time when the authentication was created) in ISO 8601 format.")],
        page_offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        page_limit: Optional[Annotated[int, Field(le=500, strict=True, ge=10)]] = None,
        filter_ids: Annotated[Optional[Annotated[List[StrictStr], Field(min_length=1, max_length=3)]], Field(description="Authentication ID. The maximum number is 3.")] = None,
        filter_status: Optional[OtpStatus] = None,
        filter_channel: Optional[OtpChannel] = None,
        filter_recipient: Optional[StrictStr] = None,
        filter_country_code: Optional[StrictStr] = None,
        way: Optional[SortWay] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[OtpList200Response]:
        """List of authentication sessions

        Use to get a list of authentications for a period.

        :param filter_from: Period start date (date and time when the authentication session was created) in ISO 8601 format. (required)
        :type filter_from: date
        :param filter_to: End date of the period (date and time when the authentication was created) in ISO 8601 format. (required)
        :type filter_to: date
        :param page_offset:
        :type page_offset: int
        :param page_limit:
        :type page_limit: int
        :param filter_ids: Authentication ID. The maximum number is 3.
        :type filter_ids: List[str]
        :param filter_status:
        :type filter_status: OtpStatus
        :param filter_channel:
        :type filter_channel: OtpChannel
        :param filter_recipient:
        :type filter_recipient: str
        :param filter_country_code:
        :type filter_country_code: str
        :param way:
        :type way: SortWay
        :param sort: Sort by
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._otp_list_serialize(
            filter_from=filter_from,
            filter_to=filter_to,
            page_offset=page_offset,
            page_limit=page_limit,
            filter_ids=filter_ids,
            filter_status=filter_status,
            filter_channel=filter_channel,
            filter_recipient=filter_recipient,
            filter_country_code=filter_country_code,
            way=way,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OtpList200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def otp_list_without_preload_content(
        self,
        filter_from: Annotated[date, Field(description="Period start date (date and time when the authentication session was created) in ISO 8601 format.")],
        filter_to: Annotated[date, Field(description="End date of the period (date and time when the authentication was created) in ISO 8601 format.")],
        page_offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        page_limit: Optional[Annotated[int, Field(le=500, strict=True, ge=10)]] = None,
        filter_ids: Annotated[Optional[Annotated[List[StrictStr], Field(min_length=1, max_length=3)]], Field(description="Authentication ID. The maximum number is 3.")] = None,
        filter_status: Optional[OtpStatus] = None,
        filter_channel: Optional[OtpChannel] = None,
        filter_recipient: Optional[StrictStr] = None,
        filter_country_code: Optional[StrictStr] = None,
        way: Optional[SortWay] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List of authentication sessions

        Use to get a list of authentications for a period.

        :param filter_from: Period start date (date and time when the authentication session was created) in ISO 8601 format. (required)
        :type filter_from: date
        :param filter_to: End date of the period (date and time when the authentication was created) in ISO 8601 format. (required)
        :type filter_to: date
        :param page_offset:
        :type page_offset: int
        :param page_limit:
        :type page_limit: int
        :param filter_ids: Authentication ID. The maximum number is 3.
        :type filter_ids: List[str]
        :param filter_status:
        :type filter_status: OtpStatus
        :param filter_channel:
        :type filter_channel: OtpChannel
        :param filter_recipient:
        :type filter_recipient: str
        :param filter_country_code:
        :type filter_country_code: str
        :param way:
        :type way: SortWay
        :param sort: Sort by
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._otp_list_serialize(
            filter_from=filter_from,
            filter_to=filter_to,
            page_offset=page_offset,
            page_limit=page_limit,
            filter_ids=filter_ids,
            filter_status=filter_status,
            filter_channel=filter_channel,
            filter_recipient=filter_recipient,
            filter_country_code=filter_country_code,
            way=way,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OtpList200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _otp_list_serialize(
        self,
        filter_from,
        filter_to,
        page_offset,
        page_limit,
        filter_ids,
        filter_status,
        filter_channel,
        filter_recipient,
        filter_country_code,
        way,
        sort,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'filter[ids]': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if page_offset is not None:
            
            _query_params.append(('page[offset]', page_offset))
            
        if page_limit is not None:
            
            _query_params.append(('page[limit]', page_limit))
            
        if filter_from is not None:
            if isinstance(filter_from, date):
                _query_params.append(
                    (
                        'filter[from]',
                        filter_from.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('filter[from]', filter_from))
            
        if filter_to is not None:
            if isinstance(filter_to, date):
                _query_params.append(
                    (
                        'filter[to]',
                        filter_to.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('filter[to]', filter_to))
            
        if filter_ids is not None:
            
            _query_params.append(('filter[ids]', filter_ids))
            
        if filter_status is not None:
            
            _query_params.append(('filter[status]', filter_status.value))
            
        if filter_channel is not None:
            
            _query_params.append(('filter[channel]', filter_channel.value))
            
        if filter_recipient is not None:
            
            _query_params.append(('filter[recipient]', filter_recipient))
            
        if filter_country_code is not None:
            
            _query_params.append(('filter[country_code]', filter_country_code))
            
        if way is not None:
            
            _query_params.append(('way', way.value))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ExternalAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/2fa/authentications',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


